version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: yarn e2e -- --protractor-config=e2e/protractor-ci.conf.js
