version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2-browsers # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test -- --watch=false
  lint:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: yarn install
      - run: yarn lint
  test:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: yarn install
      - run: yarn test
workflows:
 version: 2
 build-and-lint-and-test:
    jobs:
      - build
      - lint:
        requires:
          - build
      - test:
        requires:
          - lint
