version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.16.0-browsers
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
