version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build"
      - run: yarn install --ignore-engines
      - run: yarn build
  lint:
    docker:
      - image: circleci/node:10.9-stretch-browsers
    steps:
      - checkout
      - run: echo "Start lint"
      - run: yarn install --ignore-engines
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:10.9-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test"
      - run: yarn install --ignore-engines
      - run: yarn test
  e2e:
    docker:
      - image: circleci/node:10.9-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e"
      - run: yarn install
      - run: yarn e2e -- --no-progress --config=protractor-ci.conf.js
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
